environment:
  stack_root: 'C:\stack'

cache:
  - '%LocalAppData%\Programs\stack -> stack.yaml'
  - 'C:\stack -> stack.yaml'

before_build:
  - choco install haskell-stack

build_script:
  - stack --no-terminal --install-ghc --local-bin-path . install

after_build:
  - 7z a jc.zip jc.exe

artifacts:
  - path: jc.zip
    name: Release
